<a href="https://colab.research.google.com/github/qudrat70/programmer/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
arr=np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [3]:
arr[6]

6

In [4]:
arr2=np.arange(16).reshape(4,4)

In [5]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [13]:
arr2[1,1:]

array([5, 6, 7])

In [7]:
np.arange(64).reshape(4,4,4)

array([[[ 0,  1,  2,  3],
        [ 4,  5,  6,  7],
        [ 8,  9, 10, 11],
        [12, 13, 14, 15]],

       [[16, 17, 18, 19],
        [20, 21, 22, 23],
        [24, 25, 26, 27],
        [28, 29, 30, 31]],

       [[32, 33, 34, 35],
        [36, 37, 38, 39],
        [40, 41, 42, 43],
        [44, 45, 46, 47]],

       [[48, 49, 50, 51],
        [52, 53, 54, 55],
        [56, 57, 58, 59],
        [60, 61, 62, 63]]])

In [12]:
np.random.randint(100,size=(2,5,6))

array([[[54, 31, 60, 22, 54, 60],
        [78, 63, 32, 83, 59, 50],
        [27, 54,  0, 62, 39,  7],
        [28, 72, 36, 64, 33,  2],
        [ 2, 38, 10, 89, 25, 56]],

       [[85, 36, 18, 28, 39, 19],
        [96, 61,  5, 84,  8, 62],
        [26,  2, 18, 15, 71, 25],
        [92, 27, 73, 82, 10,  0],
        [59, 36, 94, 79, 73,  3]]])

In [14]:
arr2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [15]:
arr2*2

array([[ 0,  2,  4,  6],
       [ 8, 10, 12, 14],
       [16, 18, 20, 22],
       [24, 26, 28, 30]])

In [16]:
arr2.ndim

2

In [17]:
arr2.shape

(4, 4)

In [18]:
len(arr2)

4

In [19]:
arr2.size

16